-- ====================================================================
-- newfilebaseconnector File Connector - Seed Data & Rules
-- Version: 1.0.0
-- Date: 2026-08-07
-- Generated by: SAM Studio
-- ====================================================================

-- ====================================================================
-- SECTION 1: CONNECTOR CATEGORY REGISTRATION
-- ====================================================================

INSERT INTO core.tbl_catalog_m (
    id, tenant_id, updated_on, updated_by, created_on, created_by,
    is_deleted, data_tags, golden_key, golden_value, parent_id,
    golden_id, is_system, supporting_client_tags, golden_family, is_visible_to_client
) VALUES (
    '786be273-24f9-548b-9601-cbf55d8f03e6'::uuid,
    'c5b543aa-2701-491d-91ff-975105806193'::uuid,
    CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
    false,
    '{"Description":"File-based connector category","Type":"FILE"}',
    'ConnectorCategory', 'FILE', NULL,
    '786be273-24f9-548b-9601-cbf55d8f03e6'::uuid,
    TRUE, '{}', NULL, TRUE
) ON CONFLICT (id) DO NOTHING;

-- ====================================================================
-- SECTION 2: CONNECTOR TYPE REGISTRATION
-- ====================================================================

INSERT INTO core.tbl_catalog_m (
    id, tenant_id, updated_on, updated_by, created_on, created_by,
    is_deleted, data_tags, golden_key, golden_value, parent_id,
    golden_id, is_system, supporting_client_tags, golden_family, is_visible_to_client
) VALUES (
    'e2d6ff70-c24b-5f58-a9aa-69cad3afff4b'::uuid,
    'c5b543aa-2701-491d-91ff-975105806193'::uuid,
    CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
    false,
    '{"Description":"newfilebaseconnector File Connector","ConnectorCategory":"FILE","Version":"1.0.0"}',
    'ConnectorType', 'NewfilebaseconnectorFile', '786be273-24f9-548b-9601-cbf55d8f03e6'::uuid,
    'e2d6ff70-c24b-5f58-a9aa-69cad3afff4b'::uuid,
    TRUE, '{}', NULL, TRUE
) ON CONFLICT (id) DO NOTHING;

-- ====================================================================
-- SECTION 3: TABLE REGISTRATIONS
-- ====================================================================

-- Table: tbl_newfilebaseconnector_full_results
INSERT INTO core.tbl_catalog_m (
    id, tenant_id, updated_on, updated_by, created_on, created_by,
    is_deleted, data_tags, remarks, golden_key, golden_value,
    parent_id, golden_id, is_system, supporting_client_tags,
    golden_family, is_visible_to_client
) VALUES (
    '3c87cf4f-60bc-578e-bbf2-0b22f4a92e19'::uuid,
    'c5b543aa-2701-491d-91ff-975105806193'::uuid,
    CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
    false, '{"Description":"newfilebaseconnector full_results data"}', NULL,
    'Table', 'tbl_newfilebaseconnector_full_results',
    'e2d6ff70-c24b-5f58-a9aa-69cad3afff4b'::uuid,
    '3c87cf4f-60bc-578e-bbf2-0b22f4a92e19'::uuid,
    TRUE, '{}', 'NewfilebaseconnectorFile', TRUE
) ON CONFLICT (id) DO NOTHING;

-- ====================================================================
-- SECTION 4: COLUMN REGISTRATIONS (Key columns)
-- ====================================================================

-- Columns for tbl_newfilebaseconnector_full_results
INSERT INTO core.tbl_catalog_m (
    id, tenant_id, updated_on, updated_by, created_on, created_by,
    is_deleted, data_tags, remarks, golden_key, golden_value,
    parent_id, golden_id, is_system, supporting_client_tags,
    golden_family, is_visible_to_client
) VALUES
    ('5ed2b122-2a28-56fb-8962-b4b72a97dac7'::uuid, 'c5b543aa-2701-491d-91ff-975105806193'::uuid,
     CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
     false, '{}', 'true_page column', 'Column', 'true_page',
     '3c87cf4f-60bc-578e-bbf2-0b22f4a92e19'::uuid, '5ed2b122-2a28-56fb-8962-b4b72a97dac7'::uuid,
     TRUE, '{}', 'NewfilebaseconnectorFile', TRUE),
    ('9665a58d-9bd9-50fd-9921-aed23d549a92'::uuid, 'c5b543aa-2701-491d-91ff-975105806193'::uuid,
     CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
     false, '{}', 'json_key_used column', 'Column', 'json_key_used',
     '3c87cf4f-60bc-578e-bbf2-0b22f4a92e19'::uuid, '9665a58d-9bd9-50fd-9921-aed23d549a92'::uuid,
     TRUE, '{}', 'NewfilebaseconnectorFile', TRUE),
    ('a905776c-5321-5c9c-84b1-09f0833dbfc2'::uuid, 'c5b543aa-2701-491d-91ff-975105806193'::uuid,
     CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
     false, '{}', 'remapped column', 'Column', 'remapped',
     '3c87cf4f-60bc-578e-bbf2-0b22f4a92e19'::uuid, 'a905776c-5321-5c9c-84b1-09f0833dbfc2'::uuid,
     TRUE, '{}', 'NewfilebaseconnectorFile', TRUE),
    ('8b5855c7-ebbd-5b64-aaac-7a7347b6a40f'::uuid, 'c5b543aa-2701-491d-91ff-975105806193'::uuid,
     CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
     false, '{}', 'engine column', 'Column', 'engine',
     '3c87cf4f-60bc-578e-bbf2-0b22f4a92e19'::uuid, '8b5855c7-ebbd-5b64-aaac-7a7347b6a40f'::uuid,
     TRUE, '{}', 'NewfilebaseconnectorFile', TRUE),
    ('7b81cb3f-76b9-5bd1-9811-e4285837baa3'::uuid, 'c5b543aa-2701-491d-91ff-975105806193'::uuid,
     CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
     false, '{}', 'cer column', 'Column', 'cer',
     '3c87cf4f-60bc-578e-bbf2-0b22f4a92e19'::uuid, '7b81cb3f-76b9-5bd1-9811-e4285837baa3'::uuid,
     TRUE, '{}', 'NewfilebaseconnectorFile', TRUE),
    ('e8d3218b-8f82-599d-82e4-6116a1093e5a'::uuid, 'c5b543aa-2701-491d-91ff-975105806193'::uuid,
     CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
     false, '{}', 'wer column', 'Column', 'wer',
     '3c87cf4f-60bc-578e-bbf2-0b22f4a92e19'::uuid, 'e8d3218b-8f82-599d-82e4-6116a1093e5a'::uuid,
     TRUE, '{}', 'NewfilebaseconnectorFile', TRUE),
    ('780159fb-71df-56d2-ae52-eb2a2dc8d764'::uuid, 'c5b543aa-2701-491d-91ff-975105806193'::uuid,
     CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
     false, '{}', 'word_recall column', 'Column', 'word_recall',
     '3c87cf4f-60bc-578e-bbf2-0b22f4a92e19'::uuid, '780159fb-71df-56d2-ae52-eb2a2dc8d764'::uuid,
     TRUE, '{}', 'NewfilebaseconnectorFile', TRUE),
    ('3ef2a969-03b2-5c5b-93ef-93f9d1723a65'::uuid, 'c5b543aa-2701-491d-91ff-975105806193'::uuid,
     CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
     false, '{}', 'elapsed_s column', 'Column', 'elapsed_s',
     '3c87cf4f-60bc-578e-bbf2-0b22f4a92e19'::uuid, '3ef2a969-03b2-5c5b-93ef-93f9d1723a65'::uuid,
     TRUE, '{}', 'NewfilebaseconnectorFile', TRUE),
    ('baae2e2c-90bd-58ae-9488-8e2e76c473b1'::uuid, 'c5b543aa-2701-491d-91ff-975105806193'::uuid,
     CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
     false, '{}', 'char_count column', 'Column', 'char_count',
     '3c87cf4f-60bc-578e-bbf2-0b22f4a92e19'::uuid, 'baae2e2c-90bd-58ae-9488-8e2e76c473b1'::uuid,
     TRUE, '{}', 'NewfilebaseconnectorFile', TRUE),
    ('b29fedf2-241d-5ccd-9344-a23b0c37d3d0'::uuid, 'c5b543aa-2701-491d-91ff-975105806193'::uuid,
     CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
     false, '{}', 'provided_word_hit_ratio column', 'Column', 'provided_word_hit_ratio',
     '3c87cf4f-60bc-578e-bbf2-0b22f4a92e19'::uuid, 'b29fedf2-241d-5ccd-9344-a23b0c37d3d0'::uuid,
     TRUE, '{}', 'NewfilebaseconnectorFile', TRUE),
    ('cd0271b4-a39f-50b2-9773-30baebdb7a7c'::uuid, 'c5b543aa-2701-491d-91ff-975105806193'::uuid,
     CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
     false, '{}', 'provided_word_hits column', 'Column', 'provided_word_hits',
     '3c87cf4f-60bc-578e-bbf2-0b22f4a92e19'::uuid, 'cd0271b4-a39f-50b2-9773-30baebdb7a7c'::uuid,
     TRUE, '{}', 'NewfilebaseconnectorFile', TRUE),
    ('19271033-6f0e-5592-8c09-722b83bd1303'::uuid, 'c5b543aa-2701-491d-91ff-975105806193'::uuid,
     CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
     false, '{}', 'classification_type column', 'Column', 'classification_type',
     '3c87cf4f-60bc-578e-bbf2-0b22f4a92e19'::uuid, '19271033-6f0e-5592-8c09-722b83bd1303'::uuid,
     TRUE, '{}', 'NewfilebaseconnectorFile', TRUE),
    ('ecd36523-6881-5284-9f42-1dad54afa698'::uuid, 'c5b543aa-2701-491d-91ff-975105806193'::uuid,
     CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
     false, '{}', 'classification_confidence column', 'Column', 'classification_confidence',
     '3c87cf4f-60bc-578e-bbf2-0b22f4a92e19'::uuid, 'ecd36523-6881-5284-9f42-1dad54afa698'::uuid,
     TRUE, '{}', 'NewfilebaseconnectorFile', TRUE),
    ('80982869-e0d9-5c0d-b268-bb410868682b'::uuid, 'c5b543aa-2701-491d-91ff-975105806193'::uuid,
     CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
     false, '{}', 'gt_char_len column', 'Column', 'gt_char_len',
     '3c87cf4f-60bc-578e-bbf2-0b22f4a92e19'::uuid, '80982869-e0d9-5c0d-b268-bb410868682b'::uuid,
     TRUE, '{}', 'NewfilebaseconnectorFile', TRUE),
    ('982c11b5-ef90-5da4-b7a3-29de9463d251'::uuid, 'c5b543aa-2701-491d-91ff-975105806193'::uuid,
     CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
     false, '{}', 'hyp_char_len column', 'Column', 'hyp_char_len',
     '3c87cf4f-60bc-578e-bbf2-0b22f4a92e19'::uuid, '982c11b5-ef90-5da4-b7a3-29de9463d251'::uuid,
     TRUE, '{}', 'NewfilebaseconnectorFile', TRUE),
    ('38b1e873-f203-5c35-8f5a-9750b7a76818'::uuid, 'c5b543aa-2701-491d-91ff-975105806193'::uuid,
     CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
     false, '{}', 'expected_class column', 'Column', 'expected_class',
     '3c87cf4f-60bc-578e-bbf2-0b22f4a92e19'::uuid, '38b1e873-f203-5c35-8f5a-9750b7a76818'::uuid,
     TRUE, '{}', 'NewfilebaseconnectorFile', TRUE),
    ('dd45475a-dd83-500c-ab62-72c79b884322'::uuid, 'c5b543aa-2701-491d-91ff-975105806193'::uuid,
     CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
     false, '{}', 'class_correct column', 'Column', 'class_correct',
     '3c87cf4f-60bc-578e-bbf2-0b22f4a92e19'::uuid, 'dd45475a-dd83-500c-ab62-72c79b884322'::uuid,
     TRUE, '{}', 'NewfilebaseconnectorFile', TRUE)
ON CONFLICT (id) DO NOTHING;

-- ====================================================================
-- SECTION 5: ERROR TABLE REGISTRATION
-- ====================================================================

INSERT INTO core.tbl_catalog_m (
    id, tenant_id, updated_on, updated_by, created_on, created_by,
    is_deleted, data_tags, golden_key, golden_value,
    parent_id, golden_id, is_system, supporting_client_tags,
    golden_family, is_visible_to_client
) VALUES (
    'f7fc264c-5592-5748-b35c-c7638db596f8'::uuid,
    'c5b543aa-2701-491d-91ff-975105806193'::uuid,
    CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
    false, '{}',
    'ErrorTable', 'tbl_pre_process_newfilebaseconnector',
    'e2d6ff70-c24b-5f58-a9aa-69cad3afff4b'::uuid,
    'f7fc264c-5592-5748-b35c-c7638db596f8'::uuid,
    TRUE, '{}', 'NewfilebaseconnectorFile', TRUE
) ON CONFLICT (id) DO NOTHING;

-- ====================================================================
-- SECTION 6: PRE-PROCESSING VALIDATION RULES
-- These rules identify BAD/INVALID data in bridge tables.
-- rule_query contains the SQL condition matching rows that FAIL validation.
-- ====================================================================

-- No approved pre-processing rules defined for this connector.
-- Add rules via the SAM Studio Rules interface and re-generate.

-- ====================================================================
-- SECTION 7: POST-PROCESSING ETL RULES
-- These rules transform and load data from source to ETL schema.
-- (data flow: bridge → source → etl; ETL rules never read bridge directly)
-- All rules sharing 'SEQ1' execute together as a single group.
-- ====================================================================

-- No post-processing rules found for this connector.


-- Default source→ETL rules for tables with no field mapping configured.
-- Data flow: bridge → source → etl (ETL rules read the source schema;
-- the pre-processor promotes bridge rows to same-named source tables).
-- Review and customise before deployment.

-- Default ETL Rule 1: SKIPPED for table 'full_results' —
-- no field mapping is configured for this table, and its
-- guessed bridge name does not match any real ETL table in
-- the schema catalog. Configure a field mapping (Discovery →
-- Field Mappings) to populate this rule; the ETL target must
-- never be auto-derived from an unvalidated bridge table name.

-- ====================================================================
-- SECTION 8: CONNECTOR VERSION
-- ====================================================================

INSERT INTO core.tbl_connector_version (
    version_id, connector_type_id, version_number, created_on, created_by, is_active
) VALUES (
    '43b9cc35-cc03-55d5-b598-10bd3de2d579'::uuid,
    'e2d6ff70-c24b-5f58-a9aa-69cad3afff4b'::uuid,
    '1.0.0',
    CURRENT_TIMESTAMP,
    'System',
    TRUE
) ON CONFLICT (version_id) DO NOTHING;

-- ====================================================================
-- End of Seed Data
-- ====================================================================