-- ====================================================================
-- Microsoft 365 API Connector - Seed Data & Rules
-- Version: 1.0.0
-- Date: 2026-08-07
-- Generated by: SAM Studio
-- ====================================================================
--
-- Tenant ID: 'c5b543aa-2701-491d-91ff-975105806193'
-- All UUIDs are deterministic (UUID5) -- safe to re-run with ON CONFLICT DO NOTHING
--
-- Contents:
--   SECTION 1: Connector Category Registration (API)
--   SECTION 2: Connector Type Registration (Microsoft 365)
--   SECTION 3: Entity/Table Registrations (1 tables)
--   SECTION 4: Column Registrations (2 columns)
--   SECTION 5: Error Table Registration
--   SECTION 6: Pre-Processing Validation Rules (1 rules)
--   SECTION 7: Post-Processing ETL Rules (0 rules)
--   SECTION 8: Connector Version Registration
-- ====================================================================

-- ====================================================================
-- SECTION 1: CONNECTOR CATEGORY REGISTRATION
-- ====================================================================

INSERT INTO core.tbl_catalog_m (
    id, tenant_id, updated_on, updated_by, created_on, created_by,
    is_deleted, data_tags, golden_key, golden_value, parent_id,
    golden_id, is_system, supporting_client_tags, golden_family, is_visible_to_client
) VALUES (
    '0f377e16-a2ee-5f5f-b2f1-ed93b5e8a8a8'::uuid,
    'c5b543aa-2701-491d-91ff-975105806193'::uuid,
    CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
    false,
    '{"Description":"API-based connector category","Type":"API","SupportedAuthTypes":["OAuth2","Bearer","API Key","Basic"]}',
    'ConnectorCategory', 'API', NULL,
    '0f377e16-a2ee-5f5f-b2f1-ed93b5e8a8a8'::uuid,
    TRUE, '{}', NULL, TRUE
) ON CONFLICT (id) DO NOTHING;


-- ====================================================================
-- SECTION 2: CONNECTOR TYPE REGISTRATION
-- ====================================================================

-- Register Microsoft 365 API connector type
INSERT INTO core.tbl_catalog_m (
    id, tenant_id, updated_on, updated_by, created_on, created_by,
    is_deleted, data_tags, golden_key, golden_value, parent_id,
    golden_id, is_system, supporting_client_tags, golden_family, is_visible_to_client
) VALUES (
    '2728e7f3-30eb-54b5-b7e9-8ce17b3bd6a4'::uuid,
    'c5b543aa-2701-491d-91ff-975105806193'::uuid,
    CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
    false,
    '{"Description":"Microsoft 365 API Connector","ConnectorCategory":"API","Version":"1.0.0"}',
    'ConnectorType', 'microsoft365', '0f377e16-a2ee-5f5f-b2f1-ed93b5e8a8a8'::uuid,
    '2728e7f3-30eb-54b5-b7e9-8ce17b3bd6a4'::uuid,
    TRUE, '{}', NULL, TRUE
) ON CONFLICT (id) DO NOTHING;


-- ====================================================================
-- SECTION 3: TABLE REGISTRATIONS
-- ====================================================================

-- Entity 1: tbl_microsoft_365_subscribedskus  (endpoint: /subscribedSkus)
INSERT INTO core.tbl_catalog_m (
    id, tenant_id, updated_on, updated_by, created_on, created_by,
    is_deleted, data_tags, golden_key, golden_value, parent_id,
    golden_id, is_system, supporting_client_tags, golden_family, is_visible_to_client
) VALUES (
    '58e7e426-ed69-5cf3-bc33-8ba07355dee3'::uuid,
    'c5b543aa-2701-491d-91ff-975105806193'::uuid,
    CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
    false,
    '{"Schema":"bridge","TableName":"tbl_microsoft_365_subscribedskus","Description":"Microsoft 365 subscribedskus data","EntityType":"subscribedskus","APIEndpoint":"/subscribedSkus"}',
    'ConnectorTable', 'tbl_microsoft_365_subscribedskus', '2728e7f3-30eb-54b5-b7e9-8ce17b3bd6a4'::uuid,
    '58e7e426-ed69-5cf3-bc33-8ba07355dee3'::uuid,
    TRUE, '{}', NULL, TRUE
) ON CONFLICT (id) DO NOTHING;


-- ====================================================================
-- SECTION 4: COLUMN REGISTRATIONS
-- ====================================================================

-- Columns for tbl_microsoft_365_subscribedskus
INSERT INTO core.tbl_catalog_m (
    id, tenant_id, updated_on, updated_by, created_on, created_by,
    is_deleted, data_tags, remarks, golden_key, golden_value,
    parent_id, golden_id, is_system, supporting_client_tags,
    golden_family, is_visible_to_client
) VALUES
    ('fc94549a-26b4-59b9-9199-6957fba02c06'::uuid, 'c5b543aa-2701-491d-91ff-975105806193'::uuid, CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System', false, '{}', 'groupType', 'Column', 'grouptype', '58e7e426-ed69-5cf3-bc33-8ba07355dee3'::uuid, 'fc94549a-26b4-59b9-9199-6957fba02c06'::uuid, TRUE, '{}', 'Microsoft 365', TRUE),
    ('f1ef9418-14cb-501e-82f5-bc252bad5b8d'::uuid, 'c5b543aa-2701-491d-91ff-975105806193'::uuid, CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System', false, '{}', 'displayName', 'Column', 'displayname', '58e7e426-ed69-5cf3-bc33-8ba07355dee3'::uuid, 'f1ef9418-14cb-501e-82f5-bc252bad5b8d'::uuid, TRUE, '{}', 'Microsoft 365', TRUE)
ON CONFLICT (id) DO NOTHING;


-- ====================================================================
-- SECTION 5: ERROR TABLE REGISTRATION
-- ====================================================================

INSERT INTO core.tbl_catalog_m (
    id, tenant_id, updated_on, updated_by, created_on, created_by,
    is_deleted, data_tags, golden_key, golden_value, parent_id,
    golden_id, is_system, supporting_client_tags, golden_family, is_visible_to_client
) VALUES (
    'f65306a6-fb1c-51fe-9e9b-2f67e64ad2f7'::uuid,
    'c5b543aa-2701-491d-91ff-975105806193'::uuid,
    CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
    false,
    '{"Schema":"errors","TableName":"tbl_pre_process_microsoft_365","Description":"Error tracking for Microsoft 365 validation failures","IsErrorTable":true}',
    'ConnectorErrorTable', 'tbl_pre_process_microsoft_365', '2728e7f3-30eb-54b5-b7e9-8ce17b3bd6a4'::uuid,
    'f65306a6-fb1c-51fe-9e9b-2f67e64ad2f7'::uuid,
    TRUE, '{}', NULL, TRUE
) ON CONFLICT (id) DO NOTHING;


-- ====================================================================
-- SECTION 6: PRE-PROCESSING VALIDATION RULES
-- Data quality checks -- identifies invalid rows
-- ====================================================================

-- Rule 1: if status is disabled please drop it
INSERT INTO core.tbl_pre_processing_rule (
    id, tenant_id, updated_on, updated_by, created_on, created_by,
    is_deleted, data_tags, remarks,
    connector_type_id, table_id, column_id,
    column_priority_sequence, rule_name, rule_description, rule_query
) VALUES (
    '482b2f9a-e5e4-5177-aff0-6818399726b7'::uuid,
    'c5b543aa-2701-491d-91ff-975105806193'::uuid,
    CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
    false, '{}', 'if status is disabled please drop it',
    '2728e7f3-30eb-54b5-b7e9-8ce17b3bd6a4'::uuid,
    '58e7e426-ed69-5cf3-bc33-8ba07355dee3'::uuid,
    'fc94549a-26b4-59b9-9199-6957fba02c06'::uuid,
    1,
    'if_status_is_disabled_please_drop_it',
    'if status is disabled please drop it',
    '"status" = ''disabled'''
) ON CONFLICT (id) DO NOTHING;


-- ====================================================================
-- SECTION 7: POST-PROCESSING ETL TRANSFORMATION RULES
-- Transforms data from source to ETL/deployment schema
-- (data flow: bridge → source → etl; ETL rules never read bridge directly)
-- ====================================================================

-- No post-processing rules found for this connector.


-- Default source→ETL rules for entities with no field mapping configured.
-- Data flow: bridge → source → etl (ETL rules read the source schema;
-- the pre-processor promotes bridge rows to same-named source tables).
-- Review and customise before deployment.

-- Default ETL Rule 1: SKIPPED for entity 'subscribedskus' —
-- no field mapping is configured for this entity, and its
-- guessed bridge name does not match any real ETL table in
-- the schema catalog. Configure a field mapping (Discovery →
-- Field Mappings) to populate this rule; the ETL target must
-- never be auto-derived from an unvalidated bridge table name.


-- ====================================================================
-- SECTION 8: CONNECTOR VERSION REGISTRATION
-- ====================================================================

INSERT INTO core.tbl_connector_version (
    id, tenant_id, connector_type_id, version, release_date,
    release_notes, is_active, created_by, updated_by, created_on, updated_on
) VALUES (
    'd93120f5-497f-5623-85e5-575e2ceffaf6'::uuid,
    'c5b543aa-2701-491d-91ff-975105806193'::uuid,
    '2728e7f3-30eb-54b5-b7e9-8ce17b3bd6a4'::uuid,
    '1.0.0',
    '2026-08-07',
    'Initial release of Microsoft 365 API connector with 1 entities and 1 validation rules.',
    true,
    'System', 'System', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
) ON CONFLICT (id) DO NOTHING;

-- ====================================================================
-- END OF SEED DATA
-- ====================================================================
