-- ============================================================================
-- Microsoft 365 API Connector - Bridge Tables
-- Version: 1.0.0
-- Date: 2026-08-07
-- Generated by: SAM Studio
-- ============================================================================

-- ============================================================================
-- TABLE 1: tbl_microsoft_365_subscribedskus
-- Endpoint: /subscribedSkus
-- ============================================================================

CREATE TABLE IF NOT EXISTS bridge.tbl_microsoft_365_subscribedskus (
    -- Mandatory metadata columns (DO NOT MODIFY -- auto-populated by system)
    tenant_id UUID NOT NULL,
    connector_instance_id UUID NOT NULL,
    created_on TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    updated_on TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    is_deleted BOOLEAN DEFAULT FALSE,
    data_tags JSONB,
    remarks TEXT,
    execution_id UUID,

    -- Business columns (from /subscribedSkus API response)
    "grouptype" TEXT,
    "displayname" TEXT,

    -- Primary key
    PRIMARY KEY (tenant_id, connector_instance_id, execution_id)
);

CREATE INDEX IF NOT EXISTS idx_microsoft_365_subscribedskus_tenant
    ON bridge.tbl_microsoft_365_subscribedskus(tenant_id, connector_instance_id);
CREATE INDEX IF NOT EXISTS idx_microsoft_365_subscribedskus_exec
    ON bridge.tbl_microsoft_365_subscribedskus(execution_id);

COMMENT ON TABLE bridge.tbl_microsoft_365_subscribedskus IS 'Microsoft 365 subscribedskus data from API';

-- ============================================================================
-- ERROR TABLE -- Validation Failure Logging
-- ============================================================================

CREATE UNLOGGED TABLE IF NOT EXISTS errors.tbl_pre_process_microsoft_365 (
    id UUID NOT NULL DEFAULT uuid_generate_v4(),
    tenant_id UUID NOT NULL,
    created_on TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    created_by TEXT,
    updated_on TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    updated_by TEXT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    data_tags JSONB,
    remarks TEXT,

    -- Error-specific columns
    connector_instance_id UUID,
    execution_id TEXT,
    source_table TEXT,
    rule_id UUID,
    rule_description TEXT,
    row_id TEXT,
    failed_data JSONB,
    error_message TEXT,
    error_timestamp TIMESTAMP WITH TIME ZONE DEFAULT (NOW() AT TIME ZONE 'UTC'),
    error_type VARCHAR(100),
    severity VARCHAR(50),

    CONSTRAINT pk_tbl_pre_process_microsoft_365 PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_error_microsoft_365_tenant
    ON errors.tbl_pre_process_microsoft_365(tenant_id);
CREATE INDEX IF NOT EXISTS idx_error_microsoft_365_connector
    ON errors.tbl_pre_process_microsoft_365(connector_instance_id);
CREATE INDEX IF NOT EXISTS idx_error_microsoft_365_execution
    ON errors.tbl_pre_process_microsoft_365(execution_id);
CREATE INDEX IF NOT EXISTS idx_error_microsoft_365_table
    ON errors.tbl_pre_process_microsoft_365(source_table);
CREATE INDEX IF NOT EXISTS idx_error_microsoft_365_timestamp
    ON errors.tbl_pre_process_microsoft_365(error_timestamp);

COMMENT ON TABLE errors.tbl_pre_process_microsoft_365 IS
    'Error log for Microsoft 365 connector pre-process validation failures';

-- ============================================================================
-- GRANTS (adjust roles as needed)
-- ============================================================================
-- GRANT SELECT, INSERT, UPDATE, DELETE ON bridge.tbl_microsoft_365_subscribedskus TO connector_user;
-- GRANT SELECT, INSERT ON errors.tbl_pre_process_microsoft_365 TO connector_user;

-- ============================================================================
-- END OF MODEL.SQL
-- ============================================================================
