-- ====================================================================
-- testfile File Connector - Seed Data & Rules
-- Version: 1.0.0
-- Date: 2026-08-07
-- Generated by: SAM Studio
-- ====================================================================

-- ====================================================================
-- SECTION 1: CONNECTOR CATEGORY REGISTRATION
-- ====================================================================

INSERT INTO core.tbl_catalog_m (
    id, tenant_id, updated_on, updated_by, created_on, created_by,
    is_deleted, data_tags, golden_key, golden_value, parent_id,
    golden_id, is_system, supporting_client_tags, golden_family, is_visible_to_client
) VALUES (
    '786be273-24f9-548b-9601-cbf55d8f03e6'::uuid,
    'c5b543aa-2701-491d-91ff-975105806193'::uuid,
    CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
    false,
    '{"Description":"File-based connector category","Type":"FILE"}',
    'ConnectorCategory', 'FILE', NULL,
    '786be273-24f9-548b-9601-cbf55d8f03e6'::uuid,
    TRUE, '{}', NULL, TRUE
) ON CONFLICT (id) DO NOTHING;

-- ====================================================================
-- SECTION 2: CONNECTOR TYPE REGISTRATION
-- ====================================================================

INSERT INTO core.tbl_catalog_m (
    id, tenant_id, updated_on, updated_by, created_on, created_by,
    is_deleted, data_tags, golden_key, golden_value, parent_id,
    golden_id, is_system, supporting_client_tags, golden_family, is_visible_to_client
) VALUES (
    '1ebdbe86-eebe-57e3-abbb-2f98884aa77a'::uuid,
    'c5b543aa-2701-491d-91ff-975105806193'::uuid,
    CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
    false,
    '{"Description":"testfile File Connector","ConnectorCategory":"FILE","Version":"1.0.0"}',
    'ConnectorType', 'TestfileFile', '786be273-24f9-548b-9601-cbf55d8f03e6'::uuid,
    '1ebdbe86-eebe-57e3-abbb-2f98884aa77a'::uuid,
    TRUE, '{}', NULL, TRUE
) ON CONFLICT (id) DO NOTHING;

-- ====================================================================
-- SECTION 3: TABLE REGISTRATIONS
-- ====================================================================

-- Table: tbl_testfile_full_results
INSERT INTO core.tbl_catalog_m (
    id, tenant_id, updated_on, updated_by, created_on, created_by,
    is_deleted, data_tags, remarks, golden_key, golden_value,
    parent_id, golden_id, is_system, supporting_client_tags,
    golden_family, is_visible_to_client
) VALUES (
    '240a6652-e3c4-58b8-8f5e-105ce4e06a17'::uuid,
    'c5b543aa-2701-491d-91ff-975105806193'::uuid,
    CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
    false, '{"Description":"testfile full_results data"}', NULL,
    'Table', 'tbl_testfile_full_results',
    '1ebdbe86-eebe-57e3-abbb-2f98884aa77a'::uuid,
    '240a6652-e3c4-58b8-8f5e-105ce4e06a17'::uuid,
    TRUE, '{}', 'TestfileFile', TRUE
) ON CONFLICT (id) DO NOTHING;

-- ====================================================================
-- SECTION 4: COLUMN REGISTRATIONS (Key columns)
-- ====================================================================

-- Columns for tbl_testfile_full_results
INSERT INTO core.tbl_catalog_m (
    id, tenant_id, updated_on, updated_by, created_on, created_by,
    is_deleted, data_tags, remarks, golden_key, golden_value,
    parent_id, golden_id, is_system, supporting_client_tags,
    golden_family, is_visible_to_client
) VALUES
    ('ea88d132-ea24-54c5-988a-a3f94d10cc81'::uuid, 'c5b543aa-2701-491d-91ff-975105806193'::uuid,
     CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
     false, '{}', 'true_page column', 'Column', 'true_page',
     '240a6652-e3c4-58b8-8f5e-105ce4e06a17'::uuid, 'ea88d132-ea24-54c5-988a-a3f94d10cc81'::uuid,
     TRUE, '{}', 'TestfileFile', TRUE),
    ('05c13ae6-90c4-5180-b33c-b258845e27cc'::uuid, 'c5b543aa-2701-491d-91ff-975105806193'::uuid,
     CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
     false, '{}', 'json_key_used column', 'Column', 'json_key_used',
     '240a6652-e3c4-58b8-8f5e-105ce4e06a17'::uuid, '05c13ae6-90c4-5180-b33c-b258845e27cc'::uuid,
     TRUE, '{}', 'TestfileFile', TRUE),
    ('88da4b48-b158-5ecd-8551-233c4aabb32d'::uuid, 'c5b543aa-2701-491d-91ff-975105806193'::uuid,
     CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
     false, '{}', 'remapped column', 'Column', 'remapped',
     '240a6652-e3c4-58b8-8f5e-105ce4e06a17'::uuid, '88da4b48-b158-5ecd-8551-233c4aabb32d'::uuid,
     TRUE, '{}', 'TestfileFile', TRUE),
    ('7306eda0-19cc-5824-a5e1-623bb75c9ab5'::uuid, 'c5b543aa-2701-491d-91ff-975105806193'::uuid,
     CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
     false, '{}', 'engine column', 'Column', 'engine',
     '240a6652-e3c4-58b8-8f5e-105ce4e06a17'::uuid, '7306eda0-19cc-5824-a5e1-623bb75c9ab5'::uuid,
     TRUE, '{}', 'TestfileFile', TRUE),
    ('7c2e2ddc-053d-5d47-8375-dfdd78357d17'::uuid, 'c5b543aa-2701-491d-91ff-975105806193'::uuid,
     CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
     false, '{}', 'cer column', 'Column', 'cer',
     '240a6652-e3c4-58b8-8f5e-105ce4e06a17'::uuid, '7c2e2ddc-053d-5d47-8375-dfdd78357d17'::uuid,
     TRUE, '{}', 'TestfileFile', TRUE),
    ('3cdad4ac-bfc2-52b8-85bb-e29be3cdbd12'::uuid, 'c5b543aa-2701-491d-91ff-975105806193'::uuid,
     CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
     false, '{}', 'wer column', 'Column', 'wer',
     '240a6652-e3c4-58b8-8f5e-105ce4e06a17'::uuid, '3cdad4ac-bfc2-52b8-85bb-e29be3cdbd12'::uuid,
     TRUE, '{}', 'TestfileFile', TRUE),
    ('1247137e-f2b3-5269-838f-253d8deb1fc6'::uuid, 'c5b543aa-2701-491d-91ff-975105806193'::uuid,
     CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
     false, '{}', 'word_recall column', 'Column', 'word_recall',
     '240a6652-e3c4-58b8-8f5e-105ce4e06a17'::uuid, '1247137e-f2b3-5269-838f-253d8deb1fc6'::uuid,
     TRUE, '{}', 'TestfileFile', TRUE),
    ('0dbbf329-edf0-55b4-a253-7bee9344e4c3'::uuid, 'c5b543aa-2701-491d-91ff-975105806193'::uuid,
     CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
     false, '{}', 'elapsed_s column', 'Column', 'elapsed_s',
     '240a6652-e3c4-58b8-8f5e-105ce4e06a17'::uuid, '0dbbf329-edf0-55b4-a253-7bee9344e4c3'::uuid,
     TRUE, '{}', 'TestfileFile', TRUE),
    ('b09a9cd7-426e-5682-af5c-0b753db7389a'::uuid, 'c5b543aa-2701-491d-91ff-975105806193'::uuid,
     CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
     false, '{}', 'char_count column', 'Column', 'char_count',
     '240a6652-e3c4-58b8-8f5e-105ce4e06a17'::uuid, 'b09a9cd7-426e-5682-af5c-0b753db7389a'::uuid,
     TRUE, '{}', 'TestfileFile', TRUE),
    ('d951b7c9-549a-5bd0-ab4d-3d5f24858748'::uuid, 'c5b543aa-2701-491d-91ff-975105806193'::uuid,
     CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
     false, '{}', 'provided_word_hit_ratio column', 'Column', 'provided_word_hit_ratio',
     '240a6652-e3c4-58b8-8f5e-105ce4e06a17'::uuid, 'd951b7c9-549a-5bd0-ab4d-3d5f24858748'::uuid,
     TRUE, '{}', 'TestfileFile', TRUE),
    ('eb1a4d02-ddf7-51cf-a86c-1175211891a7'::uuid, 'c5b543aa-2701-491d-91ff-975105806193'::uuid,
     CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
     false, '{}', 'provided_word_hits column', 'Column', 'provided_word_hits',
     '240a6652-e3c4-58b8-8f5e-105ce4e06a17'::uuid, 'eb1a4d02-ddf7-51cf-a86c-1175211891a7'::uuid,
     TRUE, '{}', 'TestfileFile', TRUE),
    ('93964cd6-5142-551f-ab35-2ba341bd56f4'::uuid, 'c5b543aa-2701-491d-91ff-975105806193'::uuid,
     CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
     false, '{}', 'classification_type column', 'Column', 'classification_type',
     '240a6652-e3c4-58b8-8f5e-105ce4e06a17'::uuid, '93964cd6-5142-551f-ab35-2ba341bd56f4'::uuid,
     TRUE, '{}', 'TestfileFile', TRUE),
    ('7aa95ab5-6604-5203-92d0-091d4a367005'::uuid, 'c5b543aa-2701-491d-91ff-975105806193'::uuid,
     CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
     false, '{}', 'classification_confidence column', 'Column', 'classification_confidence',
     '240a6652-e3c4-58b8-8f5e-105ce4e06a17'::uuid, '7aa95ab5-6604-5203-92d0-091d4a367005'::uuid,
     TRUE, '{}', 'TestfileFile', TRUE),
    ('c43b0dc1-8a1e-5f05-a1a7-9d06e69b67f2'::uuid, 'c5b543aa-2701-491d-91ff-975105806193'::uuid,
     CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
     false, '{}', 'gt_char_len column', 'Column', 'gt_char_len',
     '240a6652-e3c4-58b8-8f5e-105ce4e06a17'::uuid, 'c43b0dc1-8a1e-5f05-a1a7-9d06e69b67f2'::uuid,
     TRUE, '{}', 'TestfileFile', TRUE),
    ('821652d2-76ff-5607-94e4-e363a077d830'::uuid, 'c5b543aa-2701-491d-91ff-975105806193'::uuid,
     CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
     false, '{}', 'hyp_char_len column', 'Column', 'hyp_char_len',
     '240a6652-e3c4-58b8-8f5e-105ce4e06a17'::uuid, '821652d2-76ff-5607-94e4-e363a077d830'::uuid,
     TRUE, '{}', 'TestfileFile', TRUE),
    ('a25295ec-2310-5294-b591-b70d78683923'::uuid, 'c5b543aa-2701-491d-91ff-975105806193'::uuid,
     CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
     false, '{}', 'expected_class column', 'Column', 'expected_class',
     '240a6652-e3c4-58b8-8f5e-105ce4e06a17'::uuid, 'a25295ec-2310-5294-b591-b70d78683923'::uuid,
     TRUE, '{}', 'TestfileFile', TRUE),
    ('2318e76a-8fed-5b64-8f5e-66779561a7d5'::uuid, 'c5b543aa-2701-491d-91ff-975105806193'::uuid,
     CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
     false, '{}', 'class_correct column', 'Column', 'class_correct',
     '240a6652-e3c4-58b8-8f5e-105ce4e06a17'::uuid, '2318e76a-8fed-5b64-8f5e-66779561a7d5'::uuid,
     TRUE, '{}', 'TestfileFile', TRUE)
ON CONFLICT (id) DO NOTHING;

-- ====================================================================
-- SECTION 5: ERROR TABLE REGISTRATION
-- ====================================================================

INSERT INTO core.tbl_catalog_m (
    id, tenant_id, updated_on, updated_by, created_on, created_by,
    is_deleted, data_tags, golden_key, golden_value,
    parent_id, golden_id, is_system, supporting_client_tags,
    golden_family, is_visible_to_client
) VALUES (
    'c2012354-da2d-5af4-aadb-2b5b0d657885'::uuid,
    'c5b543aa-2701-491d-91ff-975105806193'::uuid,
    CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
    false, '{}',
    'ErrorTable', 'tbl_pre_process_testfile',
    '1ebdbe86-eebe-57e3-abbb-2f98884aa77a'::uuid,
    'c2012354-da2d-5af4-aadb-2b5b0d657885'::uuid,
    TRUE, '{}', 'TestfileFile', TRUE
) ON CONFLICT (id) DO NOTHING;

-- ====================================================================
-- SECTION 6: PRE-PROCESSING VALIDATION RULES
-- These rules identify BAD/INVALID data in bridge tables.
-- rule_query contains the SQL condition matching rows that FAIL validation.
-- ====================================================================

-- No approved pre-processing rules defined for this connector.
-- Add rules via the SAM Studio Rules interface and re-generate.

-- ====================================================================
-- SECTION 7: POST-PROCESSING ETL RULES
-- These rules transform and load data from source to ETL schema.
-- (data flow: bridge → source → etl; ETL rules never read bridge directly)
-- All rules sharing 'SEQ1' execute together as a single group.
-- ====================================================================

-- No post-processing rules found for this connector.


-- Default source→ETL rules for tables with no field mapping configured.
-- Data flow: bridge → source → etl (ETL rules read the source schema;
-- the pre-processor promotes bridge rows to same-named source tables).
-- Review and customise before deployment.

-- Default ETL Rule 1: SKIPPED for table 'full_results' —
-- no field mapping is configured for this table, and its
-- guessed bridge name does not match any real ETL table in
-- the schema catalog. Configure a field mapping (Discovery →
-- Field Mappings) to populate this rule; the ETL target must
-- never be auto-derived from an unvalidated bridge table name.

-- ====================================================================
-- SECTION 8: CONNECTOR VERSION
-- ====================================================================

INSERT INTO core.tbl_connector_version (
    version_id, connector_type_id, version_number, created_on, created_by, is_active
) VALUES (
    '2e1cd46f-07d9-50db-8037-e9711604592f'::uuid,
    '1ebdbe86-eebe-57e3-abbb-2f98884aa77a'::uuid,
    '1.0.0',
    CURRENT_TIMESTAMP,
    'System',
    TRUE
) ON CONFLICT (version_id) DO NOTHING;

-- ====================================================================
-- End of Seed Data
-- ====================================================================