# 2wordcamelcase File Connector
# Version: 1.0.0
# Date: 2026-08-13
# Connector type   : 2wordcamelcasefile
# Connector category: file
# Tables           : 1
# Generated by     : SAM Studio

__version__ = "1.0.0"
__connector_category__ = "file"
__connector_type__ = "2wordcamelcasefile"
