-- ====================================================================
-- 2wordcamelcase File Connector - Seed Data & Rules
-- Version: 1.0.0
-- Date: 2026-08-13
-- Generated by: SAM Studio
-- ====================================================================

-- ====================================================================
-- SECTION 1: CONNECTOR CATEGORY REGISTRATION
-- ====================================================================

INSERT INTO core.tbl_catalog_m (
    id, tenant_id, updated_on, updated_by, created_on, created_by,
    is_deleted, data_tags, golden_key, golden_value, parent_id,
    golden_id, is_system, supporting_client_tags, golden_family, is_visible_to_client
) VALUES (
    '786be273-24f9-548b-9601-cbf55d8f03e6'::uuid,
    'c5b543aa-2701-491d-91ff-975105806193'::uuid,
    CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
    false,
    '{"Description":"File-based connector category","Type":"FILE"}',
    'ConnectorCategory', 'FILE', NULL,
    '786be273-24f9-548b-9601-cbf55d8f03e6'::uuid,
    TRUE, '{}', NULL, TRUE
) ON CONFLICT (id) DO NOTHING;

-- ====================================================================
-- SECTION 2: CONNECTOR TYPE REGISTRATION
-- ====================================================================

INSERT INTO core.tbl_catalog_m (
    id, tenant_id, updated_on, updated_by, created_on, created_by,
    is_deleted, data_tags, golden_key, golden_value, parent_id,
    golden_id, is_system, supporting_client_tags, golden_family, is_visible_to_client
) VALUES (
    '921f0e75-b3c4-583f-8cd8-0697a3d3e0c6'::uuid,
    'c5b543aa-2701-491d-91ff-975105806193'::uuid,
    CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
    false,
    '{"Description":"2wordcamelcase File Connector","ConnectorCategory":"FILE","Version":"1.0.0"}',
    'ConnectorType', '2wordcamelcaseFile', '786be273-24f9-548b-9601-cbf55d8f03e6'::uuid,
    '921f0e75-b3c4-583f-8cd8-0697a3d3e0c6'::uuid,
    TRUE, '{}', NULL, TRUE
) ON CONFLICT (id) DO NOTHING;

-- ====================================================================
-- SECTION 3: TABLE REGISTRATIONS
-- ====================================================================

-- Table: tbl_2wordcamelcase_full_results
INSERT INTO core.tbl_catalog_m (
    id, tenant_id, updated_on, updated_by, created_on, created_by,
    is_deleted, data_tags, remarks, golden_key, golden_value,
    parent_id, golden_id, is_system, supporting_client_tags,
    golden_family, is_visible_to_client
) VALUES (
    '51329e81-6ab9-55d4-b251-ff229f3c31be'::uuid,
    'c5b543aa-2701-491d-91ff-975105806193'::uuid,
    CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
    false, '{"Description":"2wordcamelcase full_results data"}', NULL,
    'Table', 'tbl_2wordcamelcase_full_results',
    '921f0e75-b3c4-583f-8cd8-0697a3d3e0c6'::uuid,
    '51329e81-6ab9-55d4-b251-ff229f3c31be'::uuid,
    TRUE, '{}', '2wordcamelcaseFile', TRUE
) ON CONFLICT (id) DO NOTHING;

-- ====================================================================
-- SECTION 4: COLUMN REGISTRATIONS (Key columns)
-- ====================================================================

-- Columns for tbl_2wordcamelcase_full_results
INSERT INTO core.tbl_catalog_m (
    id, tenant_id, updated_on, updated_by, created_on, created_by,
    is_deleted, data_tags, remarks, golden_key, golden_value,
    parent_id, golden_id, is_system, supporting_client_tags,
    golden_family, is_visible_to_client
) VALUES
    ('8a2dfd00-c61a-5cf1-a42e-6ab1ae8aadfb'::uuid, 'c5b543aa-2701-491d-91ff-975105806193'::uuid,
     CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
     false, '{}', 'true_page column', 'Column', 'true_page',
     '51329e81-6ab9-55d4-b251-ff229f3c31be'::uuid, '8a2dfd00-c61a-5cf1-a42e-6ab1ae8aadfb'::uuid,
     TRUE, '{}', '2wordcamelcaseFile', TRUE),
    ('0789ea85-051e-54e4-a134-5b5bd5739d2c'::uuid, 'c5b543aa-2701-491d-91ff-975105806193'::uuid,
     CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
     false, '{}', 'json_key_used column', 'Column', 'json_key_used',
     '51329e81-6ab9-55d4-b251-ff229f3c31be'::uuid, '0789ea85-051e-54e4-a134-5b5bd5739d2c'::uuid,
     TRUE, '{}', '2wordcamelcaseFile', TRUE),
    ('69405751-8a00-5ec1-bb2d-91d4572a109a'::uuid, 'c5b543aa-2701-491d-91ff-975105806193'::uuid,
     CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
     false, '{}', 'remapped column', 'Column', 'remapped',
     '51329e81-6ab9-55d4-b251-ff229f3c31be'::uuid, '69405751-8a00-5ec1-bb2d-91d4572a109a'::uuid,
     TRUE, '{}', '2wordcamelcaseFile', TRUE),
    ('60f6a6d6-7ca6-54ef-9a7b-34abb30e4eba'::uuid, 'c5b543aa-2701-491d-91ff-975105806193'::uuid,
     CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
     false, '{}', 'engine column', 'Column', 'engine',
     '51329e81-6ab9-55d4-b251-ff229f3c31be'::uuid, '60f6a6d6-7ca6-54ef-9a7b-34abb30e4eba'::uuid,
     TRUE, '{}', '2wordcamelcaseFile', TRUE),
    ('cf41685a-d692-53ea-9ffb-c1dfee451586'::uuid, 'c5b543aa-2701-491d-91ff-975105806193'::uuid,
     CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
     false, '{}', 'Cer column', 'Column', 'Cer',
     '51329e81-6ab9-55d4-b251-ff229f3c31be'::uuid, 'cf41685a-d692-53ea-9ffb-c1dfee451586'::uuid,
     TRUE, '{}', '2wordcamelcaseFile', TRUE),
    ('f242c3da-8e51-5ce2-b3f1-a0b0f6aba559'::uuid, 'c5b543aa-2701-491d-91ff-975105806193'::uuid,
     CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
     false, '{}', 'wer column', 'Column', 'wer',
     '51329e81-6ab9-55d4-b251-ff229f3c31be'::uuid, 'f242c3da-8e51-5ce2-b3f1-a0b0f6aba559'::uuid,
     TRUE, '{}', '2wordcamelcaseFile', TRUE),
    ('114a7a17-47b7-581c-ab82-2b9fa3de9559'::uuid, 'c5b543aa-2701-491d-91ff-975105806193'::uuid,
     CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
     false, '{}', 'WordRecall column', 'Column', 'WordRecall',
     '51329e81-6ab9-55d4-b251-ff229f3c31be'::uuid, '114a7a17-47b7-581c-ab82-2b9fa3de9559'::uuid,
     TRUE, '{}', '2wordcamelcaseFile', TRUE),
    ('26dbcff9-5bc6-509f-9ae2-c732e2e336eb'::uuid, 'c5b543aa-2701-491d-91ff-975105806193'::uuid,
     CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
     false, '{}', 'elapsedS column', 'Column', 'elapsedS',
     '51329e81-6ab9-55d4-b251-ff229f3c31be'::uuid, '26dbcff9-5bc6-509f-9ae2-c732e2e336eb'::uuid,
     TRUE, '{}', '2wordcamelcaseFile', TRUE),
    ('37d7d75d-9b9f-593a-a37b-b19d331c9283'::uuid, 'c5b543aa-2701-491d-91ff-975105806193'::uuid,
     CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
     false, '{}', 'charCount column', 'Column', 'charCount',
     '51329e81-6ab9-55d4-b251-ff229f3c31be'::uuid, '37d7d75d-9b9f-593a-a37b-b19d331c9283'::uuid,
     TRUE, '{}', '2wordcamelcaseFile', TRUE),
    ('3aedae75-aecb-5aa3-a1b4-60b804881444'::uuid, 'c5b543aa-2701-491d-91ff-975105806193'::uuid,
     CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
     false, '{}', 'provided_word_hit_ratio column', 'Column', 'provided_word_hit_ratio',
     '51329e81-6ab9-55d4-b251-ff229f3c31be'::uuid, '3aedae75-aecb-5aa3-a1b4-60b804881444'::uuid,
     TRUE, '{}', '2wordcamelcaseFile', TRUE),
    ('cc3ab7c9-168e-5aba-b127-a67535131076'::uuid, 'c5b543aa-2701-491d-91ff-975105806193'::uuid,
     CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
     false, '{}', 'provided_word_hits column', 'Column', 'provided_word_hits',
     '51329e81-6ab9-55d4-b251-ff229f3c31be'::uuid, 'cc3ab7c9-168e-5aba-b127-a67535131076'::uuid,
     TRUE, '{}', '2wordcamelcaseFile', TRUE),
    ('7f6e2cf5-76ba-53f7-b71a-7b3b80f881db'::uuid, 'c5b543aa-2701-491d-91ff-975105806193'::uuid,
     CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
     false, '{}', 'classification_Type column', 'Column', 'classification_Type',
     '51329e81-6ab9-55d4-b251-ff229f3c31be'::uuid, '7f6e2cf5-76ba-53f7-b71a-7b3b80f881db'::uuid,
     TRUE, '{}', '2wordcamelcaseFile', TRUE),
    ('0a81ccf8-69af-5490-87be-253e345d6bdb'::uuid, 'c5b543aa-2701-491d-91ff-975105806193'::uuid,
     CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
     false, '{}', 'classification_confidence column', 'Column', 'classification_confidence',
     '51329e81-6ab9-55d4-b251-ff229f3c31be'::uuid, '0a81ccf8-69af-5490-87be-253e345d6bdb'::uuid,
     TRUE, '{}', '2wordcamelcaseFile', TRUE),
    ('98c98c7d-38fe-579a-8289-ff0bc0380944'::uuid, 'c5b543aa-2701-491d-91ff-975105806193'::uuid,
     CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
     false, '{}', 'gt_char_len column', 'Column', 'gt_char_len',
     '51329e81-6ab9-55d4-b251-ff229f3c31be'::uuid, '98c98c7d-38fe-579a-8289-ff0bc0380944'::uuid,
     TRUE, '{}', '2wordcamelcaseFile', TRUE),
    ('2d598077-6dd4-541a-8e8b-92658e0f3265'::uuid, 'c5b543aa-2701-491d-91ff-975105806193'::uuid,
     CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
     false, '{}', 'hyp_char_len column', 'Column', 'hyp_char_len',
     '51329e81-6ab9-55d4-b251-ff229f3c31be'::uuid, '2d598077-6dd4-541a-8e8b-92658e0f3265'::uuid,
     TRUE, '{}', '2wordcamelcaseFile', TRUE),
    ('7cdc6a36-0589-52ee-be26-d8c1df9f7dde'::uuid, 'c5b543aa-2701-491d-91ff-975105806193'::uuid,
     CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
     false, '{}', 'expected_class column', 'Column', 'expected_class',
     '51329e81-6ab9-55d4-b251-ff229f3c31be'::uuid, '7cdc6a36-0589-52ee-be26-d8c1df9f7dde'::uuid,
     TRUE, '{}', '2wordcamelcaseFile', TRUE),
    ('dbf672de-b872-5a82-94cf-90b6ba77cf70'::uuid, 'c5b543aa-2701-491d-91ff-975105806193'::uuid,
     CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
     false, '{}', 'class_correct column', 'Column', 'class_correct',
     '51329e81-6ab9-55d4-b251-ff229f3c31be'::uuid, 'dbf672de-b872-5a82-94cf-90b6ba77cf70'::uuid,
     TRUE, '{}', '2wordcamelcaseFile', TRUE)
ON CONFLICT (id) DO NOTHING;

-- ====================================================================
-- SECTION 5: ERROR TABLE REGISTRATION
-- ====================================================================

INSERT INTO core.tbl_catalog_m (
    id, tenant_id, updated_on, updated_by, created_on, created_by,
    is_deleted, data_tags, golden_key, golden_value,
    parent_id, golden_id, is_system, supporting_client_tags,
    golden_family, is_visible_to_client
) VALUES (
    'aadaa111-3f9a-5c07-a8d3-2ce92fe700a3'::uuid,
    'c5b543aa-2701-491d-91ff-975105806193'::uuid,
    CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System',
    false, '{}',
    'ErrorTable', 'tbl_pre_process_2wordcamelcase',
    '921f0e75-b3c4-583f-8cd8-0697a3d3e0c6'::uuid,
    'aadaa111-3f9a-5c07-a8d3-2ce92fe700a3'::uuid,
    TRUE, '{}', '2wordcamelcaseFile', TRUE
) ON CONFLICT (id) DO NOTHING;

-- ====================================================================
-- SECTION 6: PRE-PROCESSING VALIDATION RULES
-- These rules identify BAD/INVALID data in bridge tables.
-- rule_query contains the SQL condition matching rows that FAIL validation.
-- ====================================================================

-- No approved pre-processing rules defined for this connector.
-- Add rules via the SAM Studio Rules interface and re-generate.

-- ====================================================================
-- SECTION 7: POST-PROCESSING ETL RULES
-- These rules transform and load data from source to ETL schema.
-- (data flow: bridge → source → etl; ETL rules never read bridge directly)
-- All rules sharing 'SEQ1' execute together as a single group.
-- ====================================================================

-- No post-processing rules found for this connector.


-- Default source→ETL rules for tables with no field mapping configured.
-- Data flow: bridge → source → etl (ETL rules read the source schema;
-- the pre-processor promotes bridge rows to same-named source tables).
-- Review and customise before deployment.

-- Default ETL Rule 1: SKIPPED for table 'full_results' —
-- no field mapping is configured for this table, and its
-- guessed bridge name does not match any real ETL table in
-- the schema catalog. Configure a field mapping (Discovery →
-- Field Mappings) to populate this rule; the ETL target must
-- never be auto-derived from an unvalidated bridge table name.

-- ====================================================================
-- SECTION 8: CONNECTOR VERSION
-- ====================================================================

INSERT INTO core.tbl_connector_version (
    version_id, connector_type_id, version_number, created_on, created_by, is_active
) VALUES (
    '0c3d1f7b-facf-5e12-b7d9-489e6993daa8'::uuid,
    '921f0e75-b3c4-583f-8cd8-0697a3d3e0c6'::uuid,
    '1.0.0',
    CURRENT_TIMESTAMP,
    'System',
    TRUE
) ON CONFLICT (version_id) DO NOTHING;

-- ====================================================================
-- End of Seed Data
-- ====================================================================